// @ts-check
import tseslint from "typescript-eslint";
import js from "@eslint/js";
import boundaries from "eslint-plugin-boundaries";

/**
 * One flat config for the whole workspace.
 *
 * The rules here are the ones that catch a class of mistake rather than a
 * style preference. Formatting is Prettier's job and is not argued about here.
 */
export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**", "**/dist/**", "**/.next/**", "**/.turbo/**",
      "**/migrations/**", "**/*.config.js", "**/*.config.ts", "eslint.config.js",
      // Generated by Next on every build; linting it is arguing with a tool.
      "**/next-env.d.ts",
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    rules: {
      // Caught by tsc with noUnusedLocals off; worth flagging since an unused
      // import is usually a leftover from a refactor that moved logic.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" },
      ],
      // `any` defeats the point of everything else here.
      "@typescript-eslint/no-explicit-any": "warn",
      "no-console": ["warn", { allow: ["warn", "error", "info"] }],
      eqeqeq: ["error", "always", { null: "ignore" }],
    },
  },

  /**
   * THE IMPORT BOUNDARY.
   *
   * CONTRIBUTING.md and docs/concepts/invariants.md both say that
   * packages/core never imports from packages/api or from an app, and that CI
   * enforces it. That claim was not true until this rule existed, which is
   * worse than not making the claim: a documented guarantee nobody checks is
   * one people rely on.
   *
   * The reason for the rule: core holds the money arithmetic, the permission
   * model, the ledger postings and the recurrence engine. All of it is pure
   * and testable without a database or a request. The moment it can reach into
   * the API layer, someone will pass a request context into a pricing function
   * and the arithmetic stops being testable in isolation.
   */
  {
    files: ["packages/core/**/*.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["@opentradesos/api", "@opentradesos/api/*", "@opentradesos/db", "@opentradesos/db/*", "@opentradesos/ui", "@opentradesos/ui/*", "next", "next/*", "react", "react/*"],
              message:
                "packages/core must stay pure: no API, database, UI or framework imports. Domain logic that needs data takes it as an argument.",
            },
            {
              group: ["../../api/*", "../../db/*", "../../../apps/*"],
              message: "packages/core must not reach into another package by relative path.",
            },
          ],
        },
      ],
    },
  },

  /** The database package owns SQL. Nothing else should import drizzle directly. */
  {
    files: ["packages/core/**/*.ts", "packages/trade-packs/**/*.ts"],
    rules: {
      "no-restricted-imports": ["error", { patterns: [{ group: ["drizzle-orm", "drizzle-orm/*", "postgres"], message: "Only packages/db and the service layer talk to the database." }] }],
    },
  },

  /** Tests may reach for anything, including a raw connection. */
  {
    files: ["**/test/**/*.ts", "**/*.test.ts"],
    rules: {
      "no-restricted-imports": "off",
      "@typescript-eslint/no-explicit-any": "off",
      "no-console": "off",
    },
  },
);
