import { randomUUID, createHash, randomBytes } from "node:crypto";
import postgres from "postgres";

/**
 * THE DEMO COMPANY
 *
 * `pnpm db:seed` turns a migrated but empty database into a company with a
 * day's work in it: a dispatch board with real gaps, a technician's route, an
 * estimate waiting on a decision, invoices in three states, and a customer
 * portal link that opens.
 *
 * It exists for three audiences, and the order matters.
 *
 * A contractor evaluating this can see the board with work on it instead of
 * an empty state, which is the difference between "I could run my shop on
 * this" and "I cannot tell".
 *
 * A contributor gets something to develop against in one command. Building a
 * plausible day by hand through the UI takes half an hour, and everybody who
 * skips it ends up testing against one customer called "test test".
 *
 * And it is the fixture the product screenshots are taken from, which means
 * the screenshots are of the actual application rendering actual rows rather
 * than of a mockup. A marketing screenshot that cannot be regenerated by a
 * command is a promise nobody is checking.
 *
 * Every id is derived from a name rather than random, so re-running updates
 * the same company instead of accumulating a new one each time.
 *
 * It writes raw SQL rather than calling the service layer, and that is a
 * layering constraint rather than a shortcut: `api` depends on `db`, so a
 * seed here that called the services would close a cycle. It also means the
 * seed keeps working when a service is mid-refactor, which is exactly when
 * somebody wants a database with data in it.
 *
 * The cost is that this file has to be kept honest by hand. The enum values
 * and the foreign keys are checked by Postgres on every run, which has caught
 * three mistakes so far, but nothing here knows about a business rule the
 * service layer enforces.
 */

const URL = process.env.DATABASE_URL ?? "postgresql://opentradesos:opentradesos@localhost:5432/opentradesos";

/**
 * WHICH TRADE THE DEMO COMPANY IS IN
 *
 * `pnpm db:seed --pack electrical` seeds an electrical shop instead of an
 * HVAC one. The price book, the job types and the company's name come from
 * the pack, and the day's work does not: the jobs, customers and invoices
 * are written as HVAC and would be nonsense on an electrician's board.
 *
 * So a non default pack seeds the CATALOGUE ONLY and stops there. That is a
 * real screen rather than a compromise: the price book is the single most
 * trade specific thing in the product, it is the first thing a contractor
 * looks at to decide whether anybody understood their trade, and it comes
 * straight out of the pack with no fixtures in between.
 *
 * Writing a day's work for eight trades is the alternative and it is not a
 * better one: eight sets of invented job summaries, by somebody who has run
 * none of those trades, is how a demo starts lying.
 */
const PACK = (() => {
  const flag = process.argv.indexOf("--pack");
  return flag === -1 ? "hvac" : (process.argv[flag + 1] ?? "hvac");
})();
const CATALOGUE_ONLY = PACK !== "hvac";

/** Stable ids from names. Re-running the seed must not duplicate anything. */
function id(name: string): string {
  const h = createHash("sha256").update(`opentradesos:seed:${name}`).digest("hex");
  return [
    h.slice(0, 8), h.slice(8, 12), `4${h.slice(13, 16)}`,
    ((parseInt(h.slice(16, 17), 16) & 0x3) | 0x8).toString(16) + h.slice(17, 20),
    h.slice(20, 32),
  ].join("-");
}

const ORG = id("org");

/**
 * The demo day is always today, and it is laid out around the current hour.
 *
 * Two mistakes are easy here and both make the board lie.
 *
 * Hardcoded dates show an empty board the day after the seed was written, and
 * somebody concludes the board is broken. Hardcoded HOURS are subtler: an
 * 8am-to-5pm day seeded at nine in the evening renders with every visit in the
 * past, so the dispatcher's "running late" badge reads four out of six and the
 * screen looks like a company in crisis rather than a company at work.
 *
 * So the day is built relative to now. The anchor is clamped into working
 * hours, because a day centred on 3am would run past midnight and split
 * across two dates, and the board is a single date.
 */
function now(): Date {
  /**
   * `SEED_NOW` pins the clock, for two reasons.
   *
   * The product screenshots have to be reproducible: run the seed at nine in
   * the evening and every visit falls behind its window, so the board renders
   * three jobs running late and looks like a company in trouble rather than a
   * company at work. Pinning the hour means the same command produces the same
   * picture on anyone's machine.
   *
   * It is also how you look at the board on a day that is not today without
   * editing this file.
   */
  const pinned = process.env["SEED_NOW"];
  if (!pinned) return new Date();
  const parsed = new Date(pinned);
  if (Number.isNaN(parsed.getTime())) {
    throw new Error(`SEED_NOW is not a date: ${JSON.stringify(pinned)}`);
  }
  return parsed;
}

/**
 * The hour the demo day is built around.
 *
 * Clamped only as far as it must be to keep the whole day inside one calendar
 * date, because the board shows one date and a day that runs past midnight
 * loses half of itself.
 *
 * The ceiling was 5pm first, which was wrong in a way that took a screenshot
 * to see: seeded at nine in the evening, the anchor snapped back four hours
 * and every visit after it fell behind a window that had already closed, so
 * the board rendered "3 running late" and looked like a company in trouble.
 * The lateness was real, and it was an artefact of the seed rather than
 * anything the product did. Anchoring near the actual hour means the day in
 * progress is genuinely in progress whenever you run it.
 */
function anchor(): Date {
  const d = now();
  // The day spans anchor minus 4.5 hours to anchor plus 3.5 hours.
  d.setHours(Math.min(20, Math.max(10, d.getHours())), 0, 0, 0);
  return d;
}

/** Hours from the anchor, so the past is done and the future is scheduled. */
function at(hoursFromAnchor: number, dayOffset = 0): Date {
  const d = anchor();
  d.setDate(d.getDate() + dayOffset);
  d.setMinutes(d.getMinutes() + Math.round(hoursFromAnchor * 60));
  return d;
}

const TECHNICIANS = [
  { key: "ray", name: "Ray Ortiz", email: "ray@ridgeline.example", color: "#1D4ED8", skills: ["hvac", "refrigerant"] },
  { key: "nia", name: "Nia Osei", email: "nia@ridgeline.example", color: "#047857", skills: ["hvac", "electrical"] },
  { key: "sam", name: "Sam Reyes", email: "sam@ridgeline.example", color: "#B45309", skills: ["hvac"] },
];

const CUSTOMERS = [
  {
    key: "whitfield", type: "residential", name: "Dana Whitfield",
    email: "dana.w@example.com", phone: "(512) 555-0192",
    address: { line1: "4102 Ramsey Ave", city: "Austin", state: "TX", postalCode: "78756" },
    gateCode: "#4417", hasDog: true, leadSource: "Referral",
  },
  {
    key: "brazos", type: "commercial", name: "Brazos Property Group",
    email: "ap@brazospg.example.com", phone: "(512) 555-0110",
    address: { line1: "900 Congress Ave", line2: "Suite 400", city: "Austin", state: "TX", postalCode: "78701" },
    leadSource: "Google", taxExempt: true, paymentTerms: 30,
  },
  {
    key: "okafor", type: "residential", name: "Tolu Okafor",
    email: "tolu.okafor@example.com", phone: "(512) 555-0177",
    address: { line1: "7300 Hart Ln", city: "Austin", state: "TX", postalCode: "78731" },
    leadSource: "Repeat customer",
  },
  {
    key: "delgado", type: "residential", name: "Marisol Delgado",
    email: "m.delgado@example.com", phone: "(512) 555-0134",
    address: { line1: "1512 Fort View Rd", city: "Austin", state: "TX", postalCode: "78704" },
    accessNotes: "Unit is on the roof. Ladder access through the side gate.",
  },
  {
    key: "kestrel", type: "commercial", name: "Kestrel Dental",
    email: "office@kestreldental.example", phone: "(512) 555-0166",
    address: { line1: "3809 Guadalupe St", city: "Austin", state: "TX", postalCode: "78751" },
    paymentTerms: 15,
  },
];

/**
 * A day with problems in it.
 *
 * A demo board where everything is assigned and on time demonstrates nothing.
 * A dispatcher's screen earns its place by showing the unassigned emergency
 * and the technician who is running late, so this day has both.
 */
const JOBS = [
  {
    key: "whitfield-maint", customer: "whitfield", summary: "Semiannual maintenance, two systems",
    type: "maintenance", status: "scheduled", tech: "ray",
    start: at(-4), end: at(-2.5), duration: 90, visitStatus: "completed",
    complaint: null, total: "344.24",
  },
  {
    key: "okafor-nocool", customer: "okafor", summary: "No cooling upstairs",
    type: "service", status: "scheduled", tech: "ray",
    start: at(-0.5), end: at(1.5), duration: 120, visitStatus: "working",
    complaint: "Upstairs will not get below 80. Downstairs is fine.", total: "0",
  },
  {
    key: "kestrel-quarterly", customer: "kestrel", summary: "Quarterly filter change, four rooftop units",
    type: "maintenance", status: "scheduled", tech: "nia",
    start: at(-4.5), end: at(-2), duration: 150, visitStatus: "completed",
    complaint: null, total: "580.00",
  },
  {
    key: "delgado-replace", customer: "delgado", summary: "Condenser replacement, 3 ton",
    type: "install", status: "scheduled", tech: "nia",
    start: at(0.5), end: at(3), duration: 150, visitStatus: "en_route",
    complaint: null, total: "6480.00",
  },
  {
    key: "brazos-suite400", customer: "brazos", summary: "Suite 400 tenant complaint, uneven temperatures",
    type: "service", status: "scheduled", tech: "sam",
    start: at(-3.5), end: at(-1.5), duration: 120, visitStatus: "completed",
    complaint: "Tenant reports the east offices run ten degrees warmer.", total: "2480.50",
  },
  {
    // The point of the board. Nobody is on this yet.
    key: "brazos-emergency", customer: "brazos", summary: "No cooling, server room",
    type: "emergency", status: "scheduled", tech: null,
    start: at(1), end: at(3), duration: 120, visitStatus: "unassigned",
    complaint: "Server room at 88F and climbing. Building manager called twice.", total: "0",
  },
  {
    key: "whitfield-followup", customer: "whitfield", summary: "Return to replace capacitor",
    type: "service", status: "scheduled", tech: "sam",
    start: at(2), end: at(3.5), duration: 90, visitStatus: "scheduled",
    complaint: null, total: "218.00",
  },
  {
    key: "okafor-tomorrow", customer: "okafor", summary: "Duct sealing, upstairs runs",
    type: "service", status: "scheduled", tech: "ray",
    start: at(-1, 1), end: at(2, 1), duration: 180, visitStatus: "scheduled",
    complaint: null, total: "0",
  },
];

async function main(): Promise<void> {
  const sql = postgres(URL, { max: 4, prepare: false });
  try {
    await wipe(sql);
    await organization(sql);
    const technicians = await people(sql);
    const jobTypes = await tradePack(sql);
    if (CATALOGUE_ONLY) {
      const owner = await session(sql, "owner");
      catalogueReport(owner);
      return;
    }
    const customers = await customersAndProperties(sql);
    await work(sql, customers, technicians, jobTypes);
    await estimate(sql, customers);
    await communications(sql, customers);
    await agreementBook(sql, customers);
    /**
     * Two sessions. The owner sees the board, the technician sees their own
     * day, and the two screens are genuinely different products for genuinely
     * different people. Seeding only the owner means the technician screen
     * never gets looked at, which is how it acquires a five hundred that
     * nobody notices.
     */
    await savedReporting(sql);
    await brand(sql);
    const links = await portalLinks(sql, customers);
    const owner = await session(sql, "owner");
    const tech = await session(sql, "ray");
    report({ owner, tech }, links);
  } finally {
    await sql.end();
  }
}

/**
 * Re-seeding replaces the demo company rather than adding a second one.
 *
 * The ledger refuses a DELETE by trigger, which is correct and is one of the
 * properties this project rests on. `session_replication_role = replica`
 * suspends user triggers for this session only, it is the standard bulk load
 * mechanism, and it is restored immediately. Nothing about the trigger
 * changes. Outside a seed or a test helper, this line would be a bug.
 */
async function wipe(sql: postgres.Sql): Promise<void> {
  const tables = await sql<{ table_name: string }[]>`
    select c.table_name from information_schema.columns c
    join information_schema.tables t
      on t.table_schema = c.table_schema and t.table_name = c.table_name
    where c.table_schema = 'public' and c.column_name = 'organization_id'
      and t.table_type = 'BASE TABLE'
  `;
  await sql.unsafe(`set session_replication_role = replica`);
  try {
    for (const { table_name } of tables) {
      await sql.unsafe(`delete from public.${table_name} where organization_id = $1`, [ORG]);
    }
    await sql.unsafe(`delete from public.session where user_id in (
      select id from public."user" where email like '%@ridgeline.example')`);
    await sql.unsafe(`delete from public."user" where email like '%@ridgeline.example'`);
    await sql.unsafe(`delete from public.organization where id = $1 or slug = 'ridgeline'`, [ORG]);
  } finally {
    await sql.unsafe(`set session_replication_role = origin`);
  }
}

async function organization(sql: postgres.Sql): Promise<void> {
  /**
   * Ridgeline is the HVAC shop the whole demo is written around. Another
   * pack gets a name of its own, because a price book full of panels and
   * conduit under a company called Ridgeline Mechanical reads as a bug.
   */
  const name = CATALOGUE_ONLY ? `Ridgeline ${titleOf(PACK)}` : "Ridgeline Mechanical";
  await sql`
    insert into public.organization (id, name, slug, legal_name, timezone, primary_trade, brand_color, setup_completed_at)
    values (${ORG}, ${name}, 'ridgeline', ${`${name} LLC`},
            'America/Chicago', ${PACK}, '#1D4ED8', now())
  `;
  await sql`
    insert into public.location (id, organization_id, name, address_line1, city, state, postal_code, timezone, is_warehouse)
    values (${id("loc")}, ${ORG}, 'Shop', '2400 Cullen Ave', 'Austin', 'TX', '78757', 'America/Chicago', true)
  `;
}

async function people(sql: postgres.Sql): Promise<Map<string, string>> {
  const owner = id("user:owner");
  await sql`insert into public."user" (id, email, name, email_verified_at)
            values (${owner}, 'owner@ridgeline.example', 'Hollis Grant', now())`;
  await sql`insert into public.membership (id, organization_id, user_id, role)
            values (${id("mem:owner")}, ${ORG}, ${owner}, 'owner')`;

  const byKey = new Map<string, string>();
  for (const tech of TECHNICIANS) {
    const userId = id(`user:${tech.key}`);
    const membershipId = id(`mem:${tech.key}`);
    const technicianId = id(`tech:${tech.key}`);
    await sql`insert into public."user" (id, email, name, email_verified_at)
              values (${userId}, ${tech.email}, ${tech.name}, now())`;
    await sql`insert into public.membership (id, organization_id, user_id, role)
              values (${membershipId}, ${ORG}, ${userId}, 'technician')`;
    await sql`insert into public.technician (id, organization_id, membership_id, display_name, color, skills, home_location_id)
              values (${technicianId}, ${ORG}, ${membershipId}, ${tech.name}, ${tech.color},
                      ${JSON.stringify(tech.skills)}, ${id("loc")})`;
    byKey.set(tech.key, technicianId);
  }
  return byKey;
}

/**
 * The HVAC pack, applied the same way the setup wizard applies it.
 *
 * Seeding job types and a price book by hand here would let this file drift
 * from what a real company gets on day one, and the demo would slowly stop
 * demonstrating the product.
 */
async function tradePack(sql: postgres.Sql): Promise<Map<string, string>> {
  const { packById, packIds } = await import("@opentradesos/trade-packs");
  const pack = packById(PACK);
  if (!pack) {
    // Named, with the list, because a typo here otherwise seeds an empty
    // price book and the first sign of it is a screen with nothing on it.
    throw new Error(`There is no trade pack called "${PACK}". There is: ${packIds.join(", ")}`);
  }

  const categories = new Map<string, string>();
  for (const item of pack.priceBook) {
    if (categories.has(item.category)) continue;
    const categoryId = id(`cat:${item.category}`);
    categories.set(item.category, categoryId);
    await sql`insert into public.price_book_category (id, organization_id, name, code)
              values (${categoryId}, ${ORG}, ${item.category}, ${item.category.toLowerCase().replace(/[^a-z0-9]+/g, "-")})`;
  }

  for (const item of pack.priceBook) {
    const itemId = id(`pb:${item.code}`);
    await sql`
      insert into public.price_book_item (id, organization_id, category_id, kind, code, trade_pack_id)
      values (${itemId}, ${ORG}, ${categories.get(item.category) ?? null}, ${item.kind}, ${item.code},
              ${`${pack.id}@${pack.version}`})
    `;
    await sql`
      insert into public.price_book_item_version
        (id, organization_id, item_id, version, name, description, price, cost, labor_minutes, taxable, tax_class, warranty_months, effective_from)
      values (${id(`pbv:${item.code}`)}, ${ORG}, ${itemId}, 1, ${item.name}, ${item.description ?? null},
              ${item.price}, ${item.cost ?? null}, ${item.laborMinutes ?? null}, ${item.taxable},
              ${item.taxClass ?? null}, ${item.warrantyMonths ?? null}, now())
    `;
  }

  const jobTypes = new Map<string, string>();
  for (const jobType of pack.jobTypes) {
    const jobTypeId = id(`jt:${jobType.code}`);
    await sql`
      insert into public.job_type (id, organization_id, name, code, capacity_model, default_duration_minutes, required_skills, color)
      values (${jobTypeId}, ${ORG}, ${jobType.name}, ${jobType.code}, ${jobType.capacityModel},
              ${jobType.defaultDurationMinutes}, ${JSON.stringify(jobType.requiredSkills)}, ${jobType.color ?? null})
    `;
    jobTypes.set(jobType.code, jobTypeId);
  }
  return jobTypes;
}

async function customersAndProperties(sql: postgres.Sql): Promise<Map<string, { customer: string; property: string }>> {
  const out = new Map<string, { customer: string; property: string }>();

  for (const c of CUSTOMERS) {
    const customerId = id(`cus:${c.key}`);
    const propertyId = id(`prop:${c.key}`);
    await sql`
      insert into public.customer
        (id, organization_id, type, name, email, phone, billing_address_line1, billing_address_line2,
         billing_city, billing_state, billing_postal_code, lead_source, payment_terms_days, tax_exempt)
      values (${customerId}, ${ORG}, ${c.type}, ${c.name}, ${c.email}, ${c.phone},
              ${c.address.line1}, ${c.address.line2 ?? null}, ${c.address.city}, ${c.address.state},
              ${c.address.postalCode}, ${c.leadSource ?? null}, ${String(c.paymentTerms ?? 0)}, ${c.taxExempt ?? false})
    `;
    await sql`
      insert into public.property
        (id, organization_id, address_line1, address_line2, city, state, postal_code, gate_code, has_dog, access_notes)
      values (${propertyId}, ${ORG}, ${c.address.line1}, ${c.address.line2 ?? null}, ${c.address.city},
              ${c.address.state}, ${c.address.postalCode}, ${c.gateCode ?? null}, ${c.hasDog ?? false},
              ${c.accessNotes ?? null})
    `;
    /**
     * The link is its own row rather than a column on the property, because a
     * property genuinely has several interested parties: an owner, a property
     * manager, and a tenant who is the one actually at the door.
     */
    await sql`
      insert into public.customer_property (id, organization_id, customer_id, property_id, role, is_primary)
      values (${id(`cp:${c.key}`)}, ${ORG}, ${customerId}, ${propertyId}, 'owner', true)
    `;
    out.set(c.key, { customer: customerId, property: propertyId });
  }
  return out;
}

async function work(
  sql: postgres.Sql,
  customers: Map<string, { customer: string; property: string }>,
  technicians: Map<string, string>,
  jobTypes: Map<string, string>,
): Promise<void> {
  let number = 1042;

  for (const spec of JOBS) {
    const link = customers.get(spec.customer);
    if (!link) throw new Error(`Seed job ${spec.key} names an unknown customer`);

    const jobId = id(`job:${spec.key}`);
    const visitId = id(`visit:${spec.key}`);
    const completed = spec.visitStatus === "completed";

    await sql`
      insert into public.job
        (id, organization_id, number, customer_id, property_id, job_type_id, status, summary,
         customer_complaint, total, completed_at)
      values (${jobId}, ${ORG}, ${number}, ${link.customer}, ${link.property},
              ${jobTypes.get(spec.type) ?? null}, ${completed ? "completed" : spec.status}, ${spec.summary},
              ${spec.complaint}, ${spec.total}, ${completed ? spec.end : null})
    `;

    await sql`
      insert into public.visit
        (id, organization_id, job_id, sequence, status, window_start, window_end,
         estimated_duration_minutes, location_id, dispatched_at, en_route_at, arrived_at, completed_at, technician_notes)
      values (${visitId}, ${ORG}, ${jobId}, 1, ${spec.visitStatus}, ${spec.start}, ${spec.end},
              ${spec.duration}, ${id("loc")},
              ${spec.tech ? spec.start : null},
              ${["en_route", "working", "completed"].includes(spec.visitStatus) ? spec.start : null},
              ${["working", "completed"].includes(spec.visitStatus) ? spec.start : null},
              ${completed ? spec.end : null},
              ${completed ? "Both systems within spec. Recommended filter change at next visit." : null})
    `;

    /**
     * THE EVENT THE COMPLETION WOULD HAVE WRITTEN.
     *
     * This file inserts rows rather than calling the services, which is the
     * right trade for a seed and left one claim in it false: the comment on
     * the automations below says the workflow path is exercised by the demo
     * rather than only by its tests, and no event was ever written, so a
     * worker running against the demo had nothing to drain and the thank you
     * text nobody got was invisible.
     *
     * Same shape `jobs.update` emits. The sequence is per organization and
     * allocated the same way, so a worker reads these exactly as it reads a
     * real one.
     */
    if (completed) {
      await sql`
        insert into public.domain_event
          (organization_id, sequence, name, entity_type, entity_id, payload, occurred_at)
        values (
          ${ORG},
          (select coalesce(max(sequence), 0) + 1 from public.domain_event where organization_id = ${ORG}),
          'job.completed', 'job', ${jobId},
          ${sql.json({
            job: {
              id: jobId, number, status: "completed", summary: spec.summary,
              customerId: link.customer, propertyId: link.property, total: spec.total,
            },
            previous: { status: "working" },
          })},
          ${spec.end}
        )
      `;
    }

    /**
     * The "on my way" notice, for the one visit that is actually en route.
     *
     * The tracking page counts down from this, so without it the customer
     * facing screen has nothing to show and the demo makes the most useful
     * thing the product does look like an empty card.
     */
    if (spec.visitStatus === "en_route") {
      const sent = new Date(now().getTime() - 6 * 60_000);
      await sql`
        insert into public.arrival_notice (id, organization_id, visit_id, channel, sent_at, eta_minutes, delivered_at)
        values (${id(`notice:${spec.key}`)}, ${ORG}, ${visitId}, 'sms', ${sent}, 25, ${sent})
      `;
    }

    if (spec.tech) {
      const technicianId = technicians.get(spec.tech);
      if (!technicianId) throw new Error(`Seed job ${spec.key} names an unknown technician`);
      await sql`
        insert into public.visit_assignment (id, organization_id, visit_id, technician_id, is_lead)
        values (${id(`va:${spec.key}`)}, ${ORG}, ${visitId}, ${technicianId}, true)
      `;
    }
    number += 1;
  }

  await invoices(sql, customers);
  await commercialArrangement(sql, customers);
}

/**
 * THE JOB WHERE THE CUSTOMER IS NOT ONE PERSON
 *
 * Every other seeded job is residential in shape: one customer who asked for
 * the work, is there for it, and pays for it. That is the case the whole
 * product was written around and it needs no parties at all.
 *
 * This is the other half of the market, and without one example of it the job
 * screen shows "nobody named" on every job in the demo, which reads as a
 * feature that does nothing. Suite 400 is a property management job: the
 * managing agent asked for it and receives the invoice, and the person the
 * technician actually rings is the tenant, who is not a customer of ours and
 * never will be.
 *
 * The ceiling is the part worth seeing move. The invoice already seeded
 * against this job is 2,480.50 against an authorised 2,500.00, so the screen
 * shows nineteen dollars fifty of room rather than an untouched limit. A
 * ceiling nothing has been billed against demonstrates nothing: the case that
 * costs contractors money is the second invoice that fits on its own and does
 * not fit on top of the first.
 */
async function commercialArrangement(
  sql: postgres.Sql,
  customers: Map<string, { customer: string; property: string }>,
): Promise<void> {
  const brazos = customers.get("brazos");
  if (!brazos) throw new Error("Seed commercial arrangement names an unknown customer");
  const jobId = id("job:brazos-suite400");

  await sql`
    insert into public.job_party
      (id, organization_id, job_id, role, customer_id, external_name, external_reference)
    values
      (${id("party:brazos-requester")}, ${ORG}, ${jobId}, 'requester', ${brazos.customer}, null, null),
      (${id("party:brazos-site")}, ${ORG}, ${jobId}, 'site_contact', null,
       'Lindmark Design, Suite 400', 'Tenant contact: Priya Raman'),
      (${id("party:brazos-billto")}, ${ORG}, ${jobId}, 'bill_to', ${brazos.customer}, null, 'AP ref 8841')
  `;

  await sql`
    insert into public.authorization
      (id, organization_id, job_id, state, amount, consumed_amount,
       granted_by_party_id, granted_by_name, external_reference, granted_at)
    values (${id("authz:brazos-suite400")}, ${ORG}, ${jobId}, 'granted', '2500.00', '2480.50',
            ${id("party:brazos-requester")}, 'Brazos, Dana Whitcomb', 'PO 44812', ${at(-6)})
  `;
}

/**
 * A number the shop can send from, and one automation that uses it.
 *
 * Without these the settings screen is three empty states, which is an honest
 * picture of an empty database and a useless picture of the product: the
 * whole point of that screen is showing whether a number may send and whether
 * an automation is on, and neither question has an answer when nothing is
 * there.
 *
 * It also means the workflow path is exercised by the demo rather than only
 * by its tests. A seed that never produces an event nobody handles is a seed
 * that would not notice the worker being broken.
 */
/**
 * A MAINTENANCE PLAN, AND TWO MEMBERS ON IT
 *
 * Without this the agreements screen is three zeroes, which is an honest
 * picture of an empty database and a useless picture of the product. The
 * whole point of that screen is the visit somebody owes and has not booked,
 * and that question has no answer when nothing is there.
 *
 * One member is mid term with a visit already delivered and the next one
 * coming due, and the other is newly sold. Between them the screen shows all
 * three states an included visit can be in.
 */
async function agreementBook(
  sql: postgres.Sql,
  customers: Map<string, { customer: string; property: string }>,
): Promise<void> {
  const planId = id("plan:comfort");
  await sql`
    insert into public.agreement_plan
      (id, organization_id, name, code, description, price, billing_frequency,
       term_months, included_visits_per_term, visit_anchor_months, discount_rate,
       priority_dispatch, waives_diagnostic_fee, benefits)
    values (${planId}, ${ORG}, 'Comfort Club', 'CC', 'Two tune ups a year, priority dispatch and no diagnostic fee.',
            '228.0000', 'monthly', 12, 2, ${sql.json([4, 10])}, '0.1000',
            true, true, ${sql.json(["Two tune ups a year", "Priority dispatch", "No diagnostic fee", "10% off repairs"])})
  `;

  const members: Array<{ key: string; startedOn: string; delivered: number }> = [
    { key: "whitfield", startedOn: monthsAgo(7), delivered: 1 },
    { key: "okafor", startedOn: monthsAgo(1), delivered: 0 },
  ];

  for (const [index, member] of members.entries()) {
    const link = customers.get(member.key);
    if (!link) throw new Error(`Seed agreement names an unknown customer: ${member.key}`);

    const agreementId = id(`agreement:${member.key}`);
    await sql`
      insert into public.agreement
        (id, organization_id, plan_id, customer_id, property_id, status, started_on,
         ends_on, price, billing_frequency, visits_included_this_term, visits_delivered_this_term)
      values (${agreementId}, ${ORG}, ${planId}, ${link.customer}, ${link.property}, 'active',
              ${member.startedOn}, ${plusMonths(member.startedOn, 12)}, '228.0000', 'monthly',
              2, ${member.delivered})
    `;

    /**
     * Two visits per term, half the price each, which is what the service
     * computes at sale. Written the same way here so the demo agrees with
     * what a real sale would produce rather than approximating it.
     */
    for (const sequence of [1, 2]) {
      const visitId = id(`agreement-visit:${member.key}:${sequence}`);
      const dueOn = plusMonths(member.startedOn, sequence === 1 ? 5 : 11);
      const delivered = sequence <= member.delivered;
      await sql`
        insert into public.agreement_visit
          (id, organization_id, agreement_id, sequence, due_on, recognition_amount,
           delivered_on, recognized_on)
        values (${visitId}, ${ORG}, ${agreementId}, ${sequence}, ${dueOn}, '114.0000',
                ${delivered ? dueOn : null}, ${delivered ? dueOn : null})
      `;
      await sql`
        insert into public.deferred_revenue_entry
          (organization_id, agreement_id, agreement_visit_id, amount, scheduled_for, recognized_on)
        values (${ORG}, ${agreementId}, ${visitId}, '114.0000', ${dueOn},
                ${delivered ? dueOn : null})
      `;
    }

    for (let instalment = 1; instalment <= 12; instalment += 1) {
      const dueOn = plusMonths(member.startedOn, instalment - 1);
      // Everything up to today is invoiced; the rest is still scheduled.
      const past = dueOn <= today();
      await sql`
        insert into public.agreement_billing
          (organization_id, agreement_id, sequence, due_on, amount, status)
        values (${ORG}, ${agreementId}, ${instalment}, ${dueOn}, '19.0000',
                ${past ? "paid" : "scheduled"})
      `;
    }

    if (index === 0) void index;
  }
}

/** Calendar helpers for the seed, in the company's own zone. */
function today(): string {
  return new Intl.DateTimeFormat("en-CA", {
    timeZone: "America/Chicago", year: "numeric", month: "2-digit", day: "2-digit",
  }).format(now());
}

function plusMonths(date: string, months: number): string {
  const [y, mo, d] = date.split("-").map(Number) as [number, number, number];
  const target = new Date(Date.UTC(y, mo - 1 + months, 1));
  const lastDay = new Date(Date.UTC(target.getUTCFullYear(), target.getUTCMonth() + 1, 0)).getUTCDate();
  target.setUTCDate(Math.min(d, lastDay));
  return target.toISOString().slice(0, 10);
}

const monthsAgo = (months: number) => plusMonths(today(), -months);

async function communications(
  sql: postgres.Sql,
  customers: Map<string, { customer: string; property: string }>,
): Promise<void> {
  await sql`
    insert into public.phone_number
      (id, organization_id, e164, label, purpose, sms_registered, capabilities)
    values (${id("number:main")}, ${ORG}, '+15125550143', 'Main line', 'main', true,
            ${sql.json({ voice: true, sms: true, mms: true })})
  `;

  /**
   * Registered, because an unregistered number is not merely rejected by the
   * carrier: the send counts against the sender. A demo that showed a number
   * sending without a campaign behind it would be teaching the wrong thing.
   */
  await sql`
    insert into public.messaging_brand (id, organization_id, legal_name, display_name, entity_type, status, approved_at)
    values (${id("brand")}, ${ORG}, 'Ridgeline Mechanical LLC', 'Ridgeline Mechanical', 'private_profit', 'approved',
            now() - interval '90 days')
  `;

  const workflowId = id("wf:completed");
  const versionId = id("wfv:completed");
  await sql`
    insert into public.workflow
      (id, organization_id, name, description, enabled, trigger_kind, trigger_events)
    values (${workflowId}, ${ORG}, 'Thank the customer when a job is done',
            'Sends one text after a completed job. Skipped for anyone who has not consented or has replied STOP.',
            true, 'event', ${sql.json(["job.completed"])})
  `;
  await sql`
    insert into public.workflow_version
      (id, organization_id, workflow_id, version, conditions, steps, required_permissions, published_at)
    values (${versionId}, ${ORG}, ${workflowId}, 1, ${sql.json({})},
            ${sql.json([{
              kind: "send_message",
              config: {
                channel: "sms",
                body: "Thanks for having us out today. Job {{ job.number }} is complete: any questions, just reply to this message.",
              },
            }])},
            ${sql.json(["message:send"])}, now())
  `;
  await sql`update public.workflow set active_version_id = ${versionId} where id = ${workflowId}`;

  /**
   * A second one on a clock, because the two trigger kinds are different
   * shapes and a demo with only the first suggests the second does not
   * exist.
   *
   * Nine in the morning on weekdays, and the schedule row is planted with it
   * so the screen can say when it next runs without waiting for a worker to
   * tick. The expression matches what the workflow holds, so a real tick
   * leaves it alone rather than replanning.
   */
  const chaseId = id("wf:chase");
  const chaseVersionId = id("wfv:chase");
  await sql`
    insert into public.workflow
      (id, organization_id, name, description, enabled, trigger_kind, trigger_events, schedule)
    values (${chaseId}, ${ORG}, 'Chase an estimate nobody answered',
            'Raises a task every weekday morning for quotes that have gone quiet.',
            true, 'schedule', ${sql.json([])}, '0 9 * * 1-5')
  `;
  await sql`
    insert into public.workflow_version
      (id, organization_id, workflow_id, version, conditions, steps, required_permissions, published_at)
    values (${chaseVersionId}, ${ORG}, ${chaseId}, 1, ${sql.json({})},
            ${sql.json([
              { kind: "wait", config: { hours: 1 } },
              { kind: "create_task", config: { title: "Follow up the quotes that have gone quiet", queue: "office", dueInHours: 8 } },
            ])},
            ${sql.json(["task:write"])}, now())
  `;
  await sql`update public.workflow set active_version_id = ${chaseVersionId} where id = ${chaseId}`;
  await sql`
    insert into public.workflow_schedule (organization_id, workflow_id, expression, next_run_at)
    values (${ORG}, ${chaseId}, '0 9 * * 1-5',
            (date_trunc('day', now() at time zone 'America/Chicago') + interval '1 day 9 hours')
              at time zone 'America/Chicago')
  `;

  /**
   * An office queue with the two shapes in it: something a person raised, and
   * something an automation did.
   *
   * A seeded queue with nothing late cannot show the one thing this screen
   * exists to answer, so one of them is a day past its due date.
   */
  /**
   * A due time an office actually works to, rather than an offset from
   * whenever the seed ran. "Due at 2:42am" reads as generated data, which is
   * the one thing this demo company is not supposed to look like.
   */
  const dueAt = (dayOffset: number, hour: number): Date => {
    const d = new Date(now());
    d.setDate(d.getDate() + dayOffset);
    d.setHours(hour, 0, 0, 0);
    return d;
  };

  const brazos = customers.get("brazos");
  const okafor = customers.get("okafor");
  const taskRows = [
    {
      key: "po",
      title: "Brazos needs a PO number before invoice 2203 can go out",
      body: "Their AP portal rejects anything without one. Ask Priya in facilities.",
      priority: "high",
      dueDay: -1, dueHour: 16,
      entity: brazos ? { type: "customer", id: brazos.customer } : null,
      queue: "office",
    },
    {
      key: "quote",
      title: "Send Tolu the duct sealing quote we promised",
      body: null,
      priority: "normal",
      dueDay: 0, dueHour: 17,
      entity: okafor ? { type: "customer", id: okafor.customer } : null,
      queue: "office",
    },
    {
      key: "callback",
      title: "Call Marisol back about the condenser warranty",
      body: "She left a voicemail asking whether the compressor is still covered.",
      priority: "normal",
      dueDay: 1, dueHour: 9,
      entity: null,
      queue: "office",
    },
  ];
  for (const t of taskRows) {
    await sql`
      insert into public.task
        (id, organization_id, title, body, priority, queue, due_at, entity_type, entity_id, created_by_user_id)
      values (${id(`task:${t.key}`)}, ${ORG}, ${t.title}, ${t.body},
              ${t.priority}::task_priority, ${t.queue},
              ${dueAt(t.dueDay, t.dueHour)},
              ${t.entity?.type ?? null}, ${t.entity?.id ?? null}, ${id("user:owner")})
    `;
  }

  /**
   * A conversation with an unanswered reply in it.
   *
   * The inbox exists to answer one question, "which of these is waiting on
   * us", and a seeded inbox with nothing waiting cannot show that it answers
   * it. This one has a reminder that went out, a reply that came back, and
   * nobody has responded.
   */
  const talking = customers.get("okafor");
  if (talking) {
    const conversationId = id("conv:okafor");
    await sql`
      insert into public.conversation
        (id, organization_id, channel, external_address, phone_number_id, customer_id,
         status, last_message_at, last_message_preview)
      values (${conversationId}, ${ORG}, 'sms', '+15125550177', ${id("number:main")},
              ${talking.customer}, 'open', ${new Date(now().getTime() - 21 * 60_000)},
              'Any chance you could make it before noon?')
    `;
    const messages = [
      { dir: "outbound", mins: 95, body: "Ridgeline Mechanical: Ray is scheduled for your no cooling call today between 1pm and 3pm. Reply to this message with any questions.", status: "delivered" },
      { dir: "inbound", mins: 21, body: "Any chance you could make it before noon?", status: "received" },
    ];
    let seq = 0;
    for (const m of messages) {
      const at = new Date(now().getTime() - m.mins * 60_000);
      await sql`
        insert into public.message
          (id, organization_id, conversation_id, direction, channel, purpose,
           from_address, to_address, body, status, sent_at, created_at)
        values (${id(`msg:okafor:${seq}`)}, ${ORG}, ${conversationId}, ${m.dir}::comm_direction,
                'sms', 'transactional',
                ${m.dir === "outbound" ? "+15125550143" : "+15125550177"},
                ${m.dir === "outbound" ? "+15125550177" : "+15125550143"},
                ${m.body}, ${m.status}::message_status, ${at}, ${at})
      `;
      seq += 1;
    }
  }

  /**
   * One customer who has consented and one who has not, because "it sends to
   * everybody" is the assumption this model exists to break. The decision is
   * made at send time against these rows, not when the workflow was written.
   */
  const consenting = customers.get("whitfield");
  if (consenting) {
    await sql`
      insert into public.communication_consent
        (id, organization_id, customer_id, address, channel, purpose, state, method, captured_at)
      values (${id("consent:whitfield")}, ${ORG}, ${consenting.customer}, '+15125550192',
              'sms', 'transactional', 'granted', 'web_form', now() - interval '60 days')
    `;
  }
}

/**
 * Receivables in three states, because an AR screen that only shows paid
 * invoices tells an owner nothing about whether they can make payroll.
 *
 * Note there is no "overdue" status, deliberately. Overdue is a fact about
 * today and a due date, not a state somebody has to remember to set. An
 * invoice that has to be marked overdue by a nightly job is an invoice that
 * is quietly not overdue whenever that job fails.
 */
async function invoices(sql: postgres.Sql, customers: Map<string, { customer: string; property: string }>): Promise<void> {
  const rows = [
    { key: "whitfield", customer: "whitfield", job: "whitfield-maint", number: 2201, status: "paid", total: "344.24", balance: "0", issued: -28, due: 2 },
    { key: "kestrel", customer: "kestrel", job: "kestrel-quarterly", number: 2202, status: "open", total: "580.00", balance: "580.00", issued: -12, due: 3 },
    // Open, and 17 days past its due date. That is what overdue is.
    { key: "brazos", customer: "brazos", job: "brazos-suite400", number: 2203, status: "open", total: "2480.50", balance: "2480.50", issued: -47, due: -17 },
  ];

  for (const row of rows) {
    const link = customers.get(row.customer);
    if (!link) continue;
    const issued = now(); issued.setDate(issued.getDate() + row.issued);
    const due = now(); due.setDate(due.getDate() + row.due);

    await sql`
      insert into public.invoice
        (id, organization_id, number, customer_id, job_id, status, issued_on, due_on,
         subtotal, tax_total, total, balance)
      values (${id(`inv:${row.key}`)}, ${ORG}, ${row.number}, ${link.customer},
              ${id(`job:${row.job}`)}, ${row.status},
              ${issued.toISOString().slice(0, 10)}, ${due.toISOString().slice(0, 10)},
              ${row.total}, '0', ${row.total}, ${row.balance})
    `;
  }

  await history(sql, customers);
}

/**
 * A YEAR OF PAID INVOICES BEHIND THE THREE LIVE ONES
 *
 * Without these the revenue trend is two columns, which is not a trend and
 * demonstrates nothing: the whole claim of that tile is that you can see the
 * shape of a year at a glance, and a chart with two buckets in it cannot make
 * that claim either way.
 *
 * All paid and none attached to a job, which is honest about what they are:
 * the book a shop already had before the demo starts. Attaching them to the
 * eight seeded jobs would put twelve invoices on one job.
 *
 * The amounts are deliberately uneven, with a summer that is roughly double
 * the winter. A flat year is a chart where a bug in the ordering, the scaling
 * or the bucketing is invisible, which is the same reason the fixtures in the
 * tests make size order and time order disagree.
 */
async function history(
  sql: postgres.Sql,
  customers: Map<string, { customer: string; property: string }>,
): Promise<void> {
  /*
    HVAC, so the shape is a Texas summer: the number is what the shop billed
    that month.

    ELEVEN of them, not twelve. The live invoices above are in the current
    month, so twelve months of history makes thirteen buckets on the trend
    and the axis reads "Sep ... Sep", which looks like a bug in the chart.
  */
  const months = [
    "16900.00", "21300.00", "28700.00", "34100.00", "41800.00",
    "46200.00", "44900.00", "38600.00", "27400.00", "22100.00", "19800.00",
  ];
  const payers = ["whitfield", "okafor", "delgado", "kestrel", "brazos"];

  let number = 2100;
  for (const [index, total] of months.entries()) {
    const link = customers.get(payers[index % payers.length]!);
    if (!link) continue;

    const issued = now();
    // The 12th of the month, so a month boundary and a timezone cannot move
    // an invoice into the bucket next door.
    issued.setMonth(issued.getMonth() - (months.length - index), 12);

    await sql`
      insert into public.invoice
        (id, organization_id, number, customer_id, status, issued_on, due_on,
         subtotal, tax_total, total, balance)
      values (${id(`inv:history:${index}`)}, ${ORG}, ${number}, ${link.customer}, 'paid',
              ${issued.toISOString().slice(0, 10)},
              ${issued.toISOString().slice(0, 10)}::date + 30,
              ${total}, '0', ${total}, '0')
    `;
    number += 1;
  }
}

/**
 * A good, better, best proposal, waiting on a decision.
 *
 * Three options rather than one number, because a single price is a yes or no
 * question and three is a which question, and the second converts better than
 * the first. The middle one is flagged recommended, which is where most
 * customers land, and that is the whole point of presenting it this way.
 */
async function estimate(sql: postgres.Sql, customers: Map<string, { customer: string; property: string }>): Promise<void> {
  const link = customers.get("delgado");
  if (!link) return;

  const estimateId = id("est:delgado");
  const expires = now();
  expires.setDate(expires.getDate() + 14);

  await sql`
    insert into public.estimate
      (id, organization_id, number, customer_id, property_id, status, title, expires_on, sent_at)
    values (${estimateId}, ${ORG}, 3101, ${link.customer}, ${link.property}, 'sent',
            'Condenser replacement, 3 ton', ${expires.toISOString().slice(0, 10)}, now())
  `;

  const options = [
    {
      key: "good", name: "Repair the existing unit", sort: 0, recommended: false, total: "1840.00",
      description: "Replace the failed compressor and recharge. Keeps the existing 11 year old condenser.",
      lines: [
        { name: "Compressor, 3 ton", qty: "1", price: "1290.00" },
        { name: "Refrigerant recovery and recharge", qty: "1", price: "380.00" },
        { name: "Diagnostic, applied to repair", qty: "1", price: "170.00" },
      ],
    },
    {
      key: "better", name: "Replace the condenser", sort: 1, recommended: true, total: "6480.00",
      description: "New 16 SEER2 condenser, matched to the existing air handler. Ten year parts warranty.",
      lines: [
        { name: "Condenser, 3 ton 16 SEER2", qty: "1", price: "4290.00" },
        { name: "Line set flush and new filter drier", qty: "1", price: "590.00" },
        { name: "Installation labour", qty: "8", price: "175.00" },
        { name: "Permit and inspection", qty: "1", price: "200.00" },
      ],
    },
    {
      key: "best", name: "Replace the full system", sort: 2, recommended: false, total: "11240.00",
      description: "New condenser and air handler, variable speed. Fixes the upstairs temperature split at the same time.",
      lines: [
        { name: "Condenser, 3 ton 17 SEER2 variable speed", qty: "1", price: "5490.00" },
        { name: "Air handler, variable speed", qty: "1", price: "3150.00" },
        { name: "Installation labour", qty: "14", price: "175.00" },
        { name: "Permit and inspection", qty: "1", price: "150.00" },
      ],
    },
  ];

  for (const option of options) {
    const optionId = id(`opt:${option.key}`);
    await sql`
      insert into public.estimate_option
        (id, organization_id, estimate_id, name, description, sort_order, is_recommended, subtotal, tax_total, total)
      values (${optionId}, ${ORG}, ${estimateId}, ${option.name}, ${option.description},
              ${option.sort}, ${option.recommended}, ${option.total}, '0', ${option.total})
    `;
    let sort = 0;
    for (const line of option.lines) {
      await sql`
        insert into public.estimate_line
          (id, organization_id, option_id, sort_order, name, quantity, unit_price, line_total, taxable)
        values (${id(`line:${option.key}:${sort}`)}, ${ORG}, ${optionId}, ${sort}, ${line.name},
                ${line.qty}, ${line.price},
                ${(Number(line.qty) * Number(line.price)).toFixed(2)}, true)
      `;
      sort += 1;
    }
  }
}

/**
 * The customer facing links.
 *
 * A capability grant, not a login. The customer never has an account, the link
 * reaches exactly one record, and it expires. Seeding them means the customer
 * side of the product can actually be opened, which otherwise sits untested
 * behind a token nobody can mint by hand.
 */
async function portalLinks(
  sql: postgres.Sql,
  customers: Map<string, { customer: string; property: string }>,
): Promise<{ estimate: string; job: string }> {
  const grant = async (scope: string, customerKey: string, subjectId: string, days: number): Promise<string> => {
    const token = randomBytes(24).toString("base64url");
    const expires = new Date();
    expires.setDate(expires.getDate() + days);
    await sql`
      insert into public.portal_grant
        (id, organization_id, customer_id, scope, subject_id, token_hash, expires_at, max_uses)
      values (${randomUUID()}, ${ORG}, ${customers.get(customerKey)?.customer ?? null}, ${scope},
              ${subjectId}, ${createHash("sha256").update(token).digest("hex")}, ${expires}, null)
    `;
    return token;
  };

  return {
    estimate: await grant("estimate", "delgado", id("est:delgado"), 14),
    job: await grant("job", "delgado", id("job:delgado-replace"), 7),
  };
}

/**
 * A session the demo can actually sign in with.
 *
 * Printed once, at the end, and never stored anywhere else. The database holds
 * the hash, so re-running the seed produces a new token rather than recovering
 * the old one, which is the property you want from session storage.
 */
async function session(sql: postgres.Sql, userKey: string): Promise<string> {
  const token = randomBytes(32).toString("base64url");
  const hash = createHash("sha256").update(token).digest("hex");
  const expires = new Date();
  expires.setDate(expires.getDate() + 30);

  await sql`
    insert into public.session (id, user_id, token_hash, active_organization_id, expires_at)
    values (${randomUUID()}, ${id(`user:${userKey}`)}, ${hash}, ${ORG}, ${expires})
  `;
  return token;
}

function report(tokens: { owner: string; tech: string }, links: { estimate: string; job: string }): void {
  const line = (label: string, value: string) => console.log(`  ${label.padEnd(14)} ${value}`);
  console.log("");
  console.log("  Ridgeline Mechanical is seeded.");
  console.log("");
  line("company", "Ridgeline Mechanical (hvac)");
  line("customers", String(CUSTOMERS.length));
  line("jobs", `${JOBS.length}, ${JOBS.filter((j) => !j.tech).length} unassigned`);
  line("technicians", TECHNICIANS.map((t) => t.name).join(", "));
  console.log("");
  console.log("  Sign in by setting the session cookie, then open the screen:");
  console.log("");
  console.log("  Hollis Grant, owner. The dispatch board at /schedule");
  console.log(`    document.cookie = "ots_session=${tokens.owner}; path=/"`);
  console.log("");
  console.log("  Ray Ortiz, technician. Their own day at /my-day");
  console.log(`    document.cookie = "ots_session=${tokens.tech}; path=/"`);
  console.log("");
  console.log("  The customer side needs no account at all. Open these directly:");
  console.log("");
  line("proposal", `/e/${links.estimate}`);
  line("job tracking", `/j/${links.job}`);
  console.log("");
}

/**
 * THE DEMO COMPANY'S OWN MARK
 *
 * `brand_color` has been set by this seed since the beginning and was read by
 * nothing. Now it reaches the screen, and a logo goes with it, because a
 * colour on its own is half the feature: the interesting claim is that the
 * product wears somebody else's name.
 *
 * A generated ring rather than a real logo. It is 371 bytes, it is obviously
 * not the OpenTradesOS mark, and it makes the point at a glance. Shipping a
 * borrowed logo in a seed would be shipping somebody else's trademark in an
 * open source repository.
 */
async function brand(sql: postgres.Sql): Promise<void> {
  const png = Buffer.from(LOGO_PNG, "base64");
  await sql`
    insert into public.brand_asset
      (id, organization_id, kind, content_type, bytes, size_bytes)
    values (${id("brand:logo")}, ${ORG}, 'logo', 'image/png', ${png}, ${png.length})
  `;
}

/** A blue ring on transparency, 64 by 64. Generated, not drawn. */
const LOGO_PNG = "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAABOklEQVR4nO2UwRECMQwDrxFaon66CQ3wSGxZkoMfenLeXW7uWWs9/zw5gHpyAPXkAOpRj73en7WzawLsCiuD2EqzYrQRrwrRUh4ZoaU4MkR7+WyEK+QzEa6Rj0a4Sj4S4Tr50wh0eadbtACRjxPrbilEVJzJYC9fzQI/ihavZmolX8E2AVBHWPJovpbySM4JkH2wSh7FOgG6vv4o3tb/PoJ5AkyACTABJsAEmACxhzlEyPLCizoH+PX7CVDxWjnKT4CTAB0ioPhgB5gRkGwTgHXIUb4kQFWIKhbZYQf5rQBZgEwIxl0KyAkU89Z2ADQYY7te1FfSTf44QIcIpz6Sj5OLfDiAY4SoRziAU4SMQyqAOgSCHRJAEQHFDQvACoHmhQeoiFHJWBogGoTJRA3gODmAenIA9eQA6n0BieNe/gGRVqEAAAAASUVORK5CYII=";

/**
 * A SAVED REPORT AND A DASHBOARD BUILT FROM IT
 *
 * Without these, both screens open on an empty state and the feature reads
 * as unfinished rather than as unused. The dashboard is the one a contractor
 * would actually assemble: the two numbers an owner checks before the week
 * starts, and the two lists they act on.
 *
 * One tile points at the saved report and the rest at reports that ship,
 * because that mix is the point. A tile is a pointer either way, so the
 * dashboard shows the report's current definition rather than a copy taken
 * the day it was added.
 */
async function savedReporting(sql: postgres.Sql): Promise<void> {
  /**
   * TWO SAVED REPORTS, BECAUSE A TILE'S SHAPE HAS TO MATCH ITS REPORT.
   *
   * A number tile needs a report with no grouping, and every report that
   * ships is grouped by something, so the headline needs one of its own.
   * The first version of this seed pointed a number tile at the receivables
   * report and the dashboard rendered it as a broken tile, correctly: the
   * API refuses that pairing, and the seed writes SQL directly so nothing
   * stopped it. Worth saying out loud, because a seed is the one place in
   * this repository that can write a row the product would not accept.
   */
  const outstanding = id("report:outstanding");
  await sql`
    insert into public.report (id, organization_id, name, description, definition)
    values (${outstanding}, ${ORG}, 'Outstanding right now',
            'Every unpaid balance on the book, as one number.',
            ${JSON.stringify({
              dataset: "invoices",
              dimensions: [],
              measures: ["balance"],
              filters: [{ dimension: "status", op: "neq", value: "paid" }],
            })}::jsonb)
  `;

  const chase = id("report:unpaid-by-customer");
  await sql`
    insert into public.report (id, organization_id, name, description, definition)
    values (${chase}, ${ORG}, 'Who to chase this week',
            'Unpaid balances by customer, biggest first.',
            ${JSON.stringify({
              dataset: "invoices",
              dimensions: ["customer"],
              measures: ["balance", "count"],
              filters: [{ dimension: "status", op: "neq", value: "paid" }],
              orderBy: "balance",
            })}::jsonb)
  `;

  await sql`
    insert into public.dashboard (id, organization_id, name, description, tiles)
    values (${id("dash:monday")}, ${ORG}, 'Monday morning',
            'What the owner checks before the week starts.',
            ${JSON.stringify([
              { key: "outstanding", kind: "number", width: 3, reportId: outstanding, title: "Outstanding" },
              { key: "chase", kind: "bars", width: 6, reportId: chase, title: "Who to chase" },
              { key: "jobs-by-status", kind: "bars", width: 6, builtIn: "jobs-by-status" },
              { key: "revenue", kind: "trend", width: 12, builtIn: "revenue-by-month" },
            ])}::jsonb)
  `;
}

/** "lawn-and-landscape" is a pack id, and a company is not called that. */
function titleOf(packId: string): string {
  return packId
    .split("-")
    .map((word) => (word === "and" ? "and" : word[0]!.toUpperCase() + word.slice(1)))
    .join(" ");
}

/**
 * What a catalogue only seed says.
 *
 * Deliberately says what is NOT there. A contributor who runs this and finds
 * an empty dispatch board should be told why in the output rather than left
 * to work out whether they broke something.
 */
function catalogueReport(token: string): void {
  console.log("");
  console.log(`  Ridgeline ${titleOf(PACK)} is seeded, price book and job types only.`);
  console.log("");
  console.log("  No jobs, customers, invoices or agreements: the day's work in this");
  console.log("  seed is written as HVAC and would be nonsense on another trade's");
  console.log("  board. Run `pnpm db:seed` with no arguments for the full company.");
  console.log("");
  console.log("  Hollis Grant, owner. The price book at /pricebook");
  console.log(`    document.cookie = "ots_session=${token}; path=/"`);
  console.log("");
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
