import { randomUUID, createHash, randomBytes } from "node:crypto";
import postgres from "postgres";

/**
 * THE DEMO COMPANY
 *
 * `pnpm db:seed` turns a migrated but empty database into a company with a
 * day's work in it: a dispatch board with real gaps, a technician's route, an
 * estimate waiting on a decision, invoices in three states, and a customer
 * portal link that opens.
 *
 * It exists for three audiences, and the order matters.
 *
 * A contractor evaluating this can see the board with work on it instead of
 * an empty state, which is the difference between "I could run my shop on
 * this" and "I cannot tell".
 *
 * A contributor gets something to develop against in one command. Building a
 * plausible day by hand through the UI takes half an hour, and everybody who
 * skips it ends up testing against one customer called "test test".
 *
 * And it is the fixture the product screenshots are taken from, which means
 * the screenshots are of the actual application rendering actual rows rather
 * than of a mockup. A marketing screenshot that cannot be regenerated by a
 * command is a promise nobody is checking.
 *
 * Every id is derived from a name rather than random, so re-running updates
 * the same company instead of accumulating a new one each time.
 */

const URL = process.env.DATABASE_URL ?? "postgresql://opentradesos:opentradesos@localhost:5432/opentradesos";

/** Stable ids from names. Re-running the seed must not duplicate anything. */
function id(name: string): string {
  const h = createHash("sha256").update(`opentradesos:seed:${name}`).digest("hex");
  return [
    h.slice(0, 8), h.slice(8, 12), `4${h.slice(13, 16)}`,
    ((parseInt(h.slice(16, 17), 16) & 0x3) | 0x8).toString(16) + h.slice(17, 20),
    h.slice(20, 32),
  ].join("-");
}

const ORG = id("org");

/**
 * The demo day is always today, and it is laid out around the current hour.
 *
 * Two mistakes are easy here and both make the board lie.
 *
 * Hardcoded dates show an empty board the day after the seed was written, and
 * somebody concludes the board is broken. Hardcoded HOURS are subtler: an
 * 8am-to-5pm day seeded at nine in the evening renders with every visit in the
 * past, so the dispatcher's "running late" badge reads four out of six and the
 * screen looks like a company in crisis rather than a company at work.
 *
 * So the day is built relative to now. The anchor is clamped into working
 * hours, because a day centred on 3am would run past midnight and split
 * across two dates, and the board is a single date.
 */
function anchor(): Date {
  const d = new Date();
  const hour = d.getHours();
  d.setHours(Math.min(17, Math.max(10, hour)), 0, 0, 0);
  return d;
}

/** Hours from the anchor, so the past is done and the future is scheduled. */
function at(hoursFromAnchor: number, dayOffset = 0): Date {
  const d = anchor();
  d.setDate(d.getDate() + dayOffset);
  d.setMinutes(d.getMinutes() + Math.round(hoursFromAnchor * 60));
  return d;
}

const TECHNICIANS = [
  { key: "ray", name: "Ray Ortiz", email: "ray@ridgeline.example", color: "#1D4ED8", skills: ["hvac", "refrigerant"] },
  { key: "nia", name: "Nia Osei", email: "nia@ridgeline.example", color: "#047857", skills: ["hvac", "electrical"] },
  { key: "sam", name: "Sam Reyes", email: "sam@ridgeline.example", color: "#B45309", skills: ["hvac"] },
];

const CUSTOMERS = [
  {
    key: "whitfield", type: "residential", name: "Dana Whitfield",
    email: "dana.w@example.com", phone: "(512) 555-0192",
    address: { line1: "4102 Ramsey Ave", city: "Austin", state: "TX", postalCode: "78756" },
    gateCode: "#4417", hasDog: true, leadSource: "Referral",
  },
  {
    key: "brazos", type: "commercial", name: "Brazos Property Group",
    email: "ap@brazospg.example.com", phone: "(512) 555-0110",
    address: { line1: "900 Congress Ave", line2: "Suite 400", city: "Austin", state: "TX", postalCode: "78701" },
    leadSource: "Google", taxExempt: true, paymentTerms: 30,
  },
  {
    key: "okafor", type: "residential", name: "Tolu Okafor",
    email: "tolu.okafor@example.com", phone: "(512) 555-0177",
    address: { line1: "7300 Hart Ln", city: "Austin", state: "TX", postalCode: "78731" },
    leadSource: "Repeat customer",
  },
  {
    key: "delgado", type: "residential", name: "Marisol Delgado",
    email: "m.delgado@example.com", phone: "(512) 555-0134",
    address: { line1: "1512 Fort View Rd", city: "Austin", state: "TX", postalCode: "78704" },
    accessNotes: "Unit is on the roof. Ladder access through the side gate.",
  },
  {
    key: "kestrel", type: "commercial", name: "Kestrel Dental",
    email: "office@kestreldental.example", phone: "(512) 555-0166",
    address: { line1: "3809 Guadalupe St", city: "Austin", state: "TX", postalCode: "78751" },
    paymentTerms: 15,
  },
];

/**
 * A day with problems in it.
 *
 * A demo board where everything is assigned and on time demonstrates nothing.
 * A dispatcher's screen earns its place by showing the unassigned emergency
 * and the technician who is running late, so this day has both.
 */
const JOBS = [
  {
    key: "whitfield-maint", customer: "whitfield", summary: "Semiannual maintenance, two systems",
    type: "maintenance", status: "scheduled", tech: "ray",
    start: at(-4), end: at(-2.5), duration: 90, visitStatus: "completed",
    complaint: null, total: "344.24",
  },
  {
    key: "okafor-nocool", customer: "okafor", summary: "No cooling upstairs",
    type: "service", status: "scheduled", tech: "ray",
    start: at(-0.5), end: at(1.5), duration: 120, visitStatus: "working",
    complaint: "Upstairs will not get below 80. Downstairs is fine.", total: "0",
  },
  {
    key: "kestrel-quarterly", customer: "kestrel", summary: "Quarterly filter change, four rooftop units",
    type: "maintenance", status: "scheduled", tech: "nia",
    start: at(-4.5), end: at(-2), duration: 150, visitStatus: "completed",
    complaint: null, total: "580.00",
  },
  {
    key: "delgado-replace", customer: "delgado", summary: "Condenser replacement, 3 ton",
    type: "install", status: "scheduled", tech: "nia",
    start: at(0.5), end: at(3), duration: 150, visitStatus: "en_route",
    complaint: null, total: "6480.00",
  },
  {
    key: "brazos-suite400", customer: "brazos", summary: "Suite 400 tenant complaint, uneven temperatures",
    type: "service", status: "scheduled", tech: "sam",
    start: at(-3.5), end: at(-1.5), duration: 120, visitStatus: "completed",
    complaint: "Tenant reports the east offices run ten degrees warmer.", total: "2480.50",
  },
  {
    // The point of the board. Nobody is on this yet.
    key: "brazos-emergency", customer: "brazos", summary: "No cooling, server room",
    type: "emergency", status: "scheduled", tech: null,
    start: at(1), end: at(3), duration: 120, visitStatus: "unassigned",
    complaint: "Server room at 88F and climbing. Building manager called twice.", total: "0",
  },
  {
    key: "whitfield-followup", customer: "whitfield", summary: "Return to replace capacitor",
    type: "service", status: "scheduled", tech: "sam",
    start: at(2), end: at(3.5), duration: 90, visitStatus: "scheduled",
    complaint: null, total: "218.00",
  },
  {
    key: "okafor-tomorrow", customer: "okafor", summary: "Duct sealing, upstairs runs",
    type: "service", status: "scheduled", tech: "ray",
    start: at(-1, 1), end: at(2, 1), duration: 180, visitStatus: "scheduled",
    complaint: null, total: "0",
  },
];

async function main(): Promise<void> {
  const sql = postgres(URL, { max: 4, prepare: false });
  try {
    await wipe(sql);
    await organization(sql);
    const technicians = await people(sql);
    const jobTypes = await tradePack(sql);
    const customers = await customersAndProperties(sql);
    await work(sql, customers, technicians, jobTypes);
    await estimate(sql, customers);
    /**
     * Two sessions. The owner sees the board, the technician sees their own
     * day, and the two screens are genuinely different products for genuinely
     * different people. Seeding only the owner means the technician screen
     * never gets looked at, which is how it acquires a five hundred that
     * nobody notices.
     */
    const links = await portalLinks(sql, customers);
    const owner = await session(sql, "owner");
    const tech = await session(sql, "ray");
    report({ owner, tech }, links);
  } finally {
    await sql.end();
  }
}

/**
 * Re-seeding replaces the demo company rather than adding a second one.
 *
 * The ledger refuses a DELETE by trigger, which is correct and is one of the
 * properties this project rests on. `session_replication_role = replica`
 * suspends user triggers for this session only, it is the standard bulk load
 * mechanism, and it is restored immediately. Nothing about the trigger
 * changes. Outside a seed or a test helper, this line would be a bug.
 */
async function wipe(sql: postgres.Sql): Promise<void> {
  const tables = await sql<{ table_name: string }[]>`
    select c.table_name from information_schema.columns c
    join information_schema.tables t
      on t.table_schema = c.table_schema and t.table_name = c.table_name
    where c.table_schema = 'public' and c.column_name = 'organization_id'
      and t.table_type = 'BASE TABLE'
  `;
  await sql.unsafe(`set session_replication_role = replica`);
  try {
    for (const { table_name } of tables) {
      await sql.unsafe(`delete from public.${table_name} where organization_id = $1`, [ORG]);
    }
    await sql.unsafe(`delete from public.session where user_id in (
      select id from public."user" where email like '%@ridgeline.example')`);
    await sql.unsafe(`delete from public."user" where email like '%@ridgeline.example'`);
    await sql.unsafe(`delete from public.organization where id = $1 or slug = 'ridgeline'`, [ORG]);
  } finally {
    await sql.unsafe(`set session_replication_role = origin`);
  }
}

async function organization(sql: postgres.Sql): Promise<void> {
  await sql`
    insert into public.organization (id, name, slug, legal_name, timezone, primary_trade, brand_color, setup_completed_at)
    values (${ORG}, 'Ridgeline Mechanical', 'ridgeline', 'Ridgeline Mechanical LLC',
            'America/Chicago', 'hvac', '#1D4ED8', now())
  `;
  await sql`
    insert into public.location (id, organization_id, name, address_line1, city, state, postal_code, timezone, is_warehouse)
    values (${id("loc")}, ${ORG}, 'Shop', '2400 Cullen Ave', 'Austin', 'TX', '78757', 'America/Chicago', true)
  `;
}

async function people(sql: postgres.Sql): Promise<Map<string, string>> {
  const owner = id("user:owner");
  await sql`insert into public."user" (id, email, name, email_verified_at)
            values (${owner}, 'owner@ridgeline.example', 'Hollis Grant', now())`;
  await sql`insert into public.membership (id, organization_id, user_id, role)
            values (${id("mem:owner")}, ${ORG}, ${owner}, 'owner')`;

  const byKey = new Map<string, string>();
  for (const tech of TECHNICIANS) {
    const userId = id(`user:${tech.key}`);
    const membershipId = id(`mem:${tech.key}`);
    const technicianId = id(`tech:${tech.key}`);
    await sql`insert into public."user" (id, email, name, email_verified_at)
              values (${userId}, ${tech.email}, ${tech.name}, now())`;
    await sql`insert into public.membership (id, organization_id, user_id, role)
              values (${membershipId}, ${ORG}, ${userId}, 'technician')`;
    await sql`insert into public.technician (id, organization_id, membership_id, display_name, color, skills, home_location_id)
              values (${technicianId}, ${ORG}, ${membershipId}, ${tech.name}, ${tech.color},
                      ${JSON.stringify(tech.skills)}, ${id("loc")})`;
    byKey.set(tech.key, technicianId);
  }
  return byKey;
}

/**
 * The HVAC pack, applied the same way the setup wizard applies it.
 *
 * Seeding job types and a price book by hand here would let this file drift
 * from what a real company gets on day one, and the demo would slowly stop
 * demonstrating the product.
 */
async function tradePack(sql: postgres.Sql): Promise<Map<string, string>> {
  const { packById } = await import("@opentradesos/trade-packs");
  const pack = packById("hvac");
  if (!pack) throw new Error("The hvac trade pack is missing");

  const categories = new Map<string, string>();
  for (const item of pack.priceBook) {
    if (categories.has(item.category)) continue;
    const categoryId = id(`cat:${item.category}`);
    categories.set(item.category, categoryId);
    await sql`insert into public.price_book_category (id, organization_id, name, code)
              values (${categoryId}, ${ORG}, ${item.category}, ${item.category.toLowerCase().replace(/[^a-z0-9]+/g, "-")})`;
  }

  for (const item of pack.priceBook) {
    const itemId = id(`pb:${item.code}`);
    await sql`
      insert into public.price_book_item (id, organization_id, category_id, kind, code, trade_pack_id)
      values (${itemId}, ${ORG}, ${categories.get(item.category) ?? null}, ${item.kind}, ${item.code},
              ${`${pack.id}@${pack.version}`})
    `;
    await sql`
      insert into public.price_book_item_version
        (id, organization_id, item_id, version, name, description, price, cost, labor_minutes, taxable, tax_class, warranty_months, effective_from)
      values (${id(`pbv:${item.code}`)}, ${ORG}, ${itemId}, 1, ${item.name}, ${item.description ?? null},
              ${item.price}, ${item.cost ?? null}, ${item.laborMinutes ?? null}, ${item.taxable},
              ${item.taxClass ?? null}, ${item.warrantyMonths ?? null}, now())
    `;
  }

  const jobTypes = new Map<string, string>();
  for (const jobType of pack.jobTypes) {
    const jobTypeId = id(`jt:${jobType.code}`);
    await sql`
      insert into public.job_type (id, organization_id, name, code, capacity_model, default_duration_minutes, required_skills, color)
      values (${jobTypeId}, ${ORG}, ${jobType.name}, ${jobType.code}, ${jobType.capacityModel},
              ${jobType.defaultDurationMinutes}, ${JSON.stringify(jobType.requiredSkills)}, ${jobType.color ?? null})
    `;
    jobTypes.set(jobType.code, jobTypeId);
  }
  return jobTypes;
}

async function customersAndProperties(sql: postgres.Sql): Promise<Map<string, { customer: string; property: string }>> {
  const out = new Map<string, { customer: string; property: string }>();

  for (const c of CUSTOMERS) {
    const customerId = id(`cus:${c.key}`);
    const propertyId = id(`prop:${c.key}`);
    await sql`
      insert into public.customer
        (id, organization_id, type, name, email, phone, billing_address_line1, billing_address_line2,
         billing_city, billing_state, billing_postal_code, lead_source, payment_terms_days, tax_exempt)
      values (${customerId}, ${ORG}, ${c.type}, ${c.name}, ${c.email}, ${c.phone},
              ${c.address.line1}, ${c.address.line2 ?? null}, ${c.address.city}, ${c.address.state},
              ${c.address.postalCode}, ${c.leadSource ?? null}, ${String(c.paymentTerms ?? 0)}, ${c.taxExempt ?? false})
    `;
    await sql`
      insert into public.property
        (id, organization_id, address_line1, address_line2, city, state, postal_code, gate_code, has_dog, access_notes)
      values (${propertyId}, ${ORG}, ${c.address.line1}, ${c.address.line2 ?? null}, ${c.address.city},
              ${c.address.state}, ${c.address.postalCode}, ${c.gateCode ?? null}, ${c.hasDog ?? false},
              ${c.accessNotes ?? null})
    `;
    /**
     * The link is its own row rather than a column on the property, because a
     * property genuinely has several interested parties: an owner, a property
     * manager, and a tenant who is the one actually at the door.
     */
    await sql`
      insert into public.customer_property (id, organization_id, customer_id, property_id, role, is_primary)
      values (${id(`cp:${c.key}`)}, ${ORG}, ${customerId}, ${propertyId}, 'owner', true)
    `;
    out.set(c.key, { customer: customerId, property: propertyId });
  }
  return out;
}

async function work(
  sql: postgres.Sql,
  customers: Map<string, { customer: string; property: string }>,
  technicians: Map<string, string>,
  jobTypes: Map<string, string>,
): Promise<void> {
  let number = 1042;

  for (const spec of JOBS) {
    const link = customers.get(spec.customer);
    if (!link) throw new Error(`Seed job ${spec.key} names an unknown customer`);

    const jobId = id(`job:${spec.key}`);
    const visitId = id(`visit:${spec.key}`);
    const completed = spec.visitStatus === "completed";

    await sql`
      insert into public.job
        (id, organization_id, number, customer_id, property_id, job_type_id, status, summary,
         customer_complaint, total, completed_at)
      values (${jobId}, ${ORG}, ${number}, ${link.customer}, ${link.property},
              ${jobTypes.get(spec.type) ?? null}, ${completed ? "completed" : spec.status}, ${spec.summary},
              ${spec.complaint}, ${spec.total}, ${completed ? spec.end : null})
    `;

    await sql`
      insert into public.visit
        (id, organization_id, job_id, sequence, status, window_start, window_end,
         estimated_duration_minutes, location_id, dispatched_at, en_route_at, arrived_at, completed_at, technician_notes)
      values (${visitId}, ${ORG}, ${jobId}, 1, ${spec.visitStatus}, ${spec.start}, ${spec.end},
              ${spec.duration}, ${id("loc")},
              ${spec.tech ? spec.start : null},
              ${["en_route", "working", "completed"].includes(spec.visitStatus) ? spec.start : null},
              ${["working", "completed"].includes(spec.visitStatus) ? spec.start : null},
              ${completed ? spec.end : null},
              ${completed ? "Both systems within spec. Recommended filter change at next visit." : null})
    `;

    /**
     * The "on my way" notice, for the one visit that is actually en route.
     *
     * The tracking page counts down from this, so without it the customer
     * facing screen has nothing to show and the demo makes the most useful
     * thing the product does look like an empty card.
     */
    if (spec.visitStatus === "en_route") {
      const sent = new Date(Date.now() - 6 * 60_000);
      await sql`
        insert into public.arrival_notice (id, organization_id, visit_id, channel, sent_at, eta_minutes, delivered_at)
        values (${id(`notice:${spec.key}`)}, ${ORG}, ${visitId}, 'sms', ${sent}, 25, ${sent})
      `;
    }

    if (spec.tech) {
      const technicianId = technicians.get(spec.tech);
      if (!technicianId) throw new Error(`Seed job ${spec.key} names an unknown technician`);
      await sql`
        insert into public.visit_assignment (id, organization_id, visit_id, technician_id, is_lead)
        values (${id(`va:${spec.key}`)}, ${ORG}, ${visitId}, ${technicianId}, true)
      `;
    }
    number += 1;
  }

  await invoices(sql, customers);
}

/**
 * Receivables in three states, because an AR screen that only shows paid
 * invoices tells an owner nothing about whether they can make payroll.
 *
 * Note there is no "overdue" status, deliberately. Overdue is a fact about
 * today and a due date, not a state somebody has to remember to set. An
 * invoice that has to be marked overdue by a nightly job is an invoice that
 * is quietly not overdue whenever that job fails.
 */
async function invoices(sql: postgres.Sql, customers: Map<string, { customer: string; property: string }>): Promise<void> {
  const rows = [
    { key: "whitfield", customer: "whitfield", job: "whitfield-maint", number: 2201, status: "paid", total: "344.24", balance: "0", issued: -28, due: 2 },
    { key: "kestrel", customer: "kestrel", job: "kestrel-quarterly", number: 2202, status: "open", total: "580.00", balance: "580.00", issued: -12, due: 3 },
    // Open, and 17 days past its due date. That is what overdue is.
    { key: "brazos", customer: "brazos", job: "brazos-suite400", number: 2203, status: "open", total: "2480.50", balance: "2480.50", issued: -47, due: -17 },
  ];

  for (const row of rows) {
    const link = customers.get(row.customer);
    if (!link) continue;
    const issued = new Date(); issued.setDate(issued.getDate() + row.issued);
    const due = new Date(); due.setDate(due.getDate() + row.due);

    await sql`
      insert into public.invoice
        (id, organization_id, number, customer_id, job_id, status, issued_on, due_on,
         subtotal, tax_total, total, balance)
      values (${id(`inv:${row.key}`)}, ${ORG}, ${row.number}, ${link.customer},
              ${id(`job:${row.job}`)}, ${row.status},
              ${issued.toISOString().slice(0, 10)}, ${due.toISOString().slice(0, 10)},
              ${row.total}, '0', ${row.total}, ${row.balance})
    `;
  }
}

/**
 * A good, better, best proposal, waiting on a decision.
 *
 * Three options rather than one number, because a single price is a yes or no
 * question and three is a which question, and the second converts better than
 * the first. The middle one is flagged recommended, which is where most
 * customers land, and that is the whole point of presenting it this way.
 */
async function estimate(sql: postgres.Sql, customers: Map<string, { customer: string; property: string }>): Promise<void> {
  const link = customers.get("delgado");
  if (!link) return;

  const estimateId = id("est:delgado");
  const expires = new Date();
  expires.setDate(expires.getDate() + 14);

  await sql`
    insert into public.estimate
      (id, organization_id, number, customer_id, property_id, status, title, expires_on, sent_at)
    values (${estimateId}, ${ORG}, 3101, ${link.customer}, ${link.property}, 'sent',
            'Condenser replacement, 3 ton', ${expires.toISOString().slice(0, 10)}, now())
  `;

  const options = [
    {
      key: "good", name: "Repair the existing unit", sort: 0, recommended: false, total: "1840.00",
      description: "Replace the failed compressor and recharge. Keeps the existing 11 year old condenser.",
      lines: [
        { name: "Compressor, 3 ton", qty: "1", price: "1290.00" },
        { name: "Refrigerant recovery and recharge", qty: "1", price: "380.00" },
        { name: "Diagnostic, applied to repair", qty: "1", price: "170.00" },
      ],
    },
    {
      key: "better", name: "Replace the condenser", sort: 1, recommended: true, total: "6480.00",
      description: "New 16 SEER2 condenser, matched to the existing air handler. Ten year parts warranty.",
      lines: [
        { name: "Condenser, 3 ton 16 SEER2", qty: "1", price: "4290.00" },
        { name: "Line set flush and new filter drier", qty: "1", price: "590.00" },
        { name: "Installation labour", qty: "8", price: "175.00" },
        { name: "Permit and inspection", qty: "1", price: "200.00" },
      ],
    },
    {
      key: "best", name: "Replace the full system", sort: 2, recommended: false, total: "11240.00",
      description: "New condenser and air handler, variable speed. Fixes the upstairs temperature split at the same time.",
      lines: [
        { name: "Condenser, 3 ton 17 SEER2 variable speed", qty: "1", price: "5490.00" },
        { name: "Air handler, variable speed", qty: "1", price: "3150.00" },
        { name: "Installation labour", qty: "14", price: "175.00" },
        { name: "Permit and inspection", qty: "1", price: "150.00" },
      ],
    },
  ];

  for (const option of options) {
    const optionId = id(`opt:${option.key}`);
    await sql`
      insert into public.estimate_option
        (id, organization_id, estimate_id, name, description, sort_order, is_recommended, subtotal, tax_total, total)
      values (${optionId}, ${ORG}, ${estimateId}, ${option.name}, ${option.description},
              ${option.sort}, ${option.recommended}, ${option.total}, '0', ${option.total})
    `;
    let sort = 0;
    for (const line of option.lines) {
      await sql`
        insert into public.estimate_line
          (id, organization_id, option_id, sort_order, name, quantity, unit_price, line_total, taxable)
        values (${id(`line:${option.key}:${sort}`)}, ${ORG}, ${optionId}, ${sort}, ${line.name},
                ${line.qty}, ${line.price},
                ${(Number(line.qty) * Number(line.price)).toFixed(2)}, true)
      `;
      sort += 1;
    }
  }
}

/**
 * The customer facing links.
 *
 * A capability grant, not a login. The customer never has an account, the link
 * reaches exactly one record, and it expires. Seeding them means the customer
 * side of the product can actually be opened, which otherwise sits untested
 * behind a token nobody can mint by hand.
 */
async function portalLinks(
  sql: postgres.Sql,
  customers: Map<string, { customer: string; property: string }>,
): Promise<{ estimate: string; job: string }> {
  const grant = async (scope: string, customerKey: string, subjectId: string, days: number): Promise<string> => {
    const token = randomBytes(24).toString("base64url");
    const expires = new Date();
    expires.setDate(expires.getDate() + days);
    await sql`
      insert into public.portal_grant
        (id, organization_id, customer_id, scope, subject_id, token_hash, expires_at, max_uses)
      values (${randomUUID()}, ${ORG}, ${customers.get(customerKey)?.customer ?? null}, ${scope},
              ${subjectId}, ${createHash("sha256").update(token).digest("hex")}, ${expires}, null)
    `;
    return token;
  };

  return {
    estimate: await grant("estimate", "delgado", id("est:delgado"), 14),
    job: await grant("job", "delgado", id("job:delgado-replace"), 7),
  };
}

/**
 * A session the demo can actually sign in with.
 *
 * Printed once, at the end, and never stored anywhere else. The database holds
 * the hash, so re-running the seed produces a new token rather than recovering
 * the old one, which is the property you want from session storage.
 */
async function session(sql: postgres.Sql, userKey: string): Promise<string> {
  const token = randomBytes(32).toString("base64url");
  const hash = createHash("sha256").update(token).digest("hex");
  const expires = new Date();
  expires.setDate(expires.getDate() + 30);

  await sql`
    insert into public.session (id, user_id, token_hash, active_organization_id, expires_at)
    values (${randomUUID()}, ${id(`user:${userKey}`)}, ${hash}, ${ORG}, ${expires})
  `;
  return token;
}

function report(tokens: { owner: string; tech: string }, links: { estimate: string; job: string }): void {
  const line = (label: string, value: string) => console.log(`  ${label.padEnd(14)} ${value}`);
  console.log("");
  console.log("  Ridgeline Mechanical is seeded.");
  console.log("");
  line("company", "Ridgeline Mechanical (hvac)");
  line("customers", String(CUSTOMERS.length));
  line("jobs", `${JOBS.length}, ${JOBS.filter((j) => !j.tech).length} unassigned`);
  line("technicians", TECHNICIANS.map((t) => t.name).join(", "));
  console.log("");
  console.log("  Sign in by setting the session cookie, then open the screen:");
  console.log("");
  console.log("  Hollis Grant, owner. The dispatch board at /schedule");
  console.log(`    document.cookie = "ots_session=${tokens.owner}; path=/"`);
  console.log("");
  console.log("  Ray Ortiz, technician. Their own day at /my-day");
  console.log(`    document.cookie = "ots_session=${tokens.tech}; path=/"`);
  console.log("");
  console.log("  The customer side needs no account at all. Open these directly:");
  console.log("");
  line("proposal", `/e/${links.estimate}`);
  line("job tracking", `/j/${links.job}`);
  console.log("");
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
